# Generated by Django 3.2.8 on 2021-10-26 20:44

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutmeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=150, verbose_name='متن اول')),
                ('text2', models.CharField(max_length=1000, verbose_name='متن دوم')),
                ('fullname', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('age', models.CharField(max_length=150, verbose_name='سن')),
                ('experience', models.CharField(max_length=150, verbose_name='تجربه')),
                ('country', models.CharField(max_length=150, verbose_name='کشور')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('city', models.CharField(max_length=150, verbose_name='شهر')),
                ('email', models.CharField(max_length=150, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'تنظیمات درباره ی من',
                'verbose_name_plural': 'مدیریت تنظیمات درباره ی من',
            },
        ),
        migrations.CreateModel(
            name='HeaderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=150, verbose_name='نام صفحه')),
                ('home_link', models.CharField(max_length=150, verbose_name='لینک صفحه')),
                ('about', models.CharField(max_length=150, verbose_name='نام صفحه')),
                ('about_link', models.CharField(max_length=150, verbose_name='لینک صفحه')),
                ('skill', models.CharField(max_length=150, verbose_name='نام صفحه')),
                ('skill_link', models.CharField(max_length=150, verbose_name='لینک صفحه')),
                ('resume', models.CharField(max_length=150, verbose_name='نام صفحه')),
                ('resume_link', models.CharField(max_length=150, verbose_name='لینک صفحه')),
                ('portfolio', models.CharField(max_length=150, verbose_name='نام صفحه')),
                ('portfolio_link', models.CharField(max_length=150, verbose_name='لینک صفحه')),
                ('contact', models.CharField(max_length=150, verbose_name='نام صفحه')),
                ('contact_link', models.CharField(max_length=150, verbose_name='لینک صفحه')),
            ],
            options={
                'verbose_name': 'تنظیمات هدر و منوی سایت',
                'verbose_name_plural': 'مدیریت تنظیمات هدر و منوی سایت',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_right', models.CharField(max_length=150, verbose_name='حق کپی رایت')),
                ('twitter', models.CharField(max_length=150, verbose_name='لینک توییتر')),
                ('instagram', models.CharField(max_length=150, verbose_name='لینک اینستاگرام')),
                ('linkedin', models.CharField(max_length=150, verbose_name='لینک لینکدین')),
                ('github', models.CharField(max_length=150, verbose_name='لینک گیت هاب')),
            ],
            options={
                'verbose_name': 'تنظیمات انتهای سایت',
                'verbose_name_plural': 'مدیریت تنظیمات لینک شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='SkillSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2', models.CharField(max_length=150, verbose_name='عنوان تیتر اصلی')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مهارت')),
                ('description', models.CharField(max_length=150, verbose_name='توضیحات مهارت')),
                ('svg', models.FileField(default=False, upload_to='images', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='فایل svg')),
                ('width', models.IntegerField(max_length=5, null=True, verbose_name='طول svg')),
                ('width_px_percent', models.CharField(max_length=2, null=True, verbose_name='اندازه بر اساس px یا %')),
                ('height', models.IntegerField(max_length=5, null=True, verbose_name='ارتفاع svg')),
                ('height_px_percent', models.CharField(max_length=2, null=True, verbose_name='اندازه بر اساس px یا %')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='انتخاب رنگ پس زمینه')),
            ],
            options={
                'verbose_name': 'تنظیمات مهارت ها',
                'verbose_name_plural': 'مدیریت تنظیمات مهارت ها',
            },
        ),
        migrations.CreateModel(
            name='SlideSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=150, verbose_name='متن اول')),
                ('text2', models.CharField(max_length=150, verbose_name='متن دوم')),
                ('text3', models.CharField(max_length=150, verbose_name='متن سوم')),
            ],
            options={
                'verbose_name': 'تنظیمات اسلاید',
                'verbose_name_plural': 'مدیریت تنظیمات اسلاید',
            },
        ),
    ]
