# Generated by Django 3.2.8 on 2021-10-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amirhossein_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsetting',
            name='color',
        ),
        migrations.AlterField(
            model_name='skillsetting',
            name='height',
            field=models.CharField(max_length=5, null=True, verbose_name='ارتفاع svg'),
        ),
        migrations.AlterField(
            model_name='skillsetting',
            name='width',
            field=models.CharField(max_length=5, null=True, verbose_name='طول svg'),
        ),
    ]
