# Generated by Django 3.2.8 on 2021-10-26 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amirhossein_settings', '0002_auto_20211027_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsetting',
            name='h2',
        ),
    ]
