# Generated by Django 3.2.8 on 2021-10-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amirhossein_settings', '0003_remove_skillsetting_h2'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='عنوان')),
                ('date', models.CharField(max_length=150, null=True, verbose_name='بازه زمانی')),
                ('description', models.CharField(max_length=150, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تنظیمات تحصیلات',
                'verbose_name_plural': 'مدیریا تنظیمات تحصیلات',
            },
        ),
    ]
