# Generated by Django 3.2.8 on 2021-10-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amirhossein_settings', '0004_educationsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='عنوان')),
                ('date', models.CharField(max_length=150, null=True, verbose_name='بازه زمانی')),
                ('description', models.CharField(max_length=850, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تنظیمات تجربه\u200cها',
                'verbose_name_plural': 'مدیریت تنظیمات تجربه\u200cها',
            },
        ),
        migrations.AlterField(
            model_name='educationsetting',
            name='description',
            field=models.CharField(max_length=850, null=True, verbose_name='توضیحات'),
        ),
    ]
