# Generated by Django 3.2.8 on 2021-10-27 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amirhossein_settings', '0005_auto_20211027_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان پروژه')),
                ('description', models.CharField(max_length=150, verbose_name='توضیحات پروژه')),
                ('svg', models.FileField(default=False, upload_to='images', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='فایل svg')),
                ('width', models.CharField(max_length=5, null=True, verbose_name='طول svg')),
                ('width_px_percent', models.CharField(max_length=2, null=True, verbose_name='اندازه بر اساس px یا %')),
                ('height', models.CharField(max_length=5, null=True, verbose_name='ارتفاع svg')),
                ('height_px_percent', models.CharField(max_length=2, null=True, verbose_name='اندازه بر اساس px یا %')),
            ],
        ),
    ]
